apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: optimizer
  region: ap-northeast-2
  version: "1.20"

managedNodeGroups:
  - name: develop
    instanceType: t3.medium
    privateNetworking: true
    minSize: 8
    maxSize: 10
    desiredCapacity: 8
    volumeSize: 50
    availabilityZones: ['ap-northeast-2a', 'ap-northeast-2d', 'ap-northeast-2c']
    ssh:
      allow: true
      publicKeyName: airflow-workstation
    labels: { role: develop }
    tags:
      nodegroup-role: develop
    iam:
      withAddonPolicies:
        ebs: true
        imageBuilder: true
        efs: true
        albIngress: true
        autoScaler: true
        cloudWatch: true
        externalDNS: true
  - name: worker
    instanceType: t3.medium
    privateNetworking: true
    minSize: 5
    maxSize: 5
    desiredCapacity: 5
    volumeSize: 50
    availabilityZones: ['ap-northeast-2a', 'ap-northeast-2d', 'ap-northeast-2c']
    ssh:
      allow: true
      publicKeyName: airflow-workstation
    labels: { role: worker }
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        ebs: true
        imageBuilder: true
        efs: true
        albIngress: true
        autoScaler: true
        cloudWatch: true
        externalDNS: true
  - name: train
    instanceType: c5.2xlarge
    privateNetworking: true
    minSize: 1
    maxSize : 30
    desiredCapacity: 1
    volumeSize: 100
    availabilityZones: ['ap-northeast-2a', 'ap-northeast-2c']
    ssh:
      allow: true
      publicKeyName: airflow-workstation
    labels: { role: train }
    tags:
      nodegroup-role: train
    iam:
      withAddonPolicies:
        ebs: true
        imageBuilder: true
        efs: true
        albIngress: true
        autoScaler: true
        cloudWatch: true
        externalDNS: true
  - name: auth-server
    instanceType: t3.medium
    privateNetworking: true
    minSize: 3
    maxSize: 3
    desiredCapacity: 3
    volumeSize: 20
    availabilityZones: ['ap-northeast-2a', 'ap-northeast-2c']
    ssh:
      allow: true
      publicKeyName: airflow-workstation
    labels: { role: auth }
    tags:
      nodegroup-role: auth
    iam:
      withAddonPolicies:
        ebs: true
        imageBuilder: true
        efs: true
        albIngress: true
        autoScaler: true
        cloudWatch: true
        externalDNS: true
  - name: inference-server
    instanceType: t3.medium
    privateNetworking: true
    minSize: 1
    maxSize: 20
    desiredCapacity: 1
    volumeSize: 50
    availabilityZones: ['ap-northeast-2a','ap-northeast-2d', 'ap-northeast-2c']
    ssh:
      allow: true
      publicKeyName: airflow-workstation
    labels: { role: inference }
    tags:
      nodegroup-role: inference
    iam:
      withAddonPolicies:
        ebs: true
        imageBuilder: true
        efs: true
        albIngress: true
        autoScaler: true
        cloudWatch: true
        externalDNS: true
  - name: manager
    instanceType: t3.large
    privateNetworking: true
    minSize: 8
    maxSize: 8
    desiredCapacity: 8
    volumeSize: 20
    availabilityZones: ['ap-northeast-2a', 'ap-northeast-2d', 'ap-northeast-2c']
    ssh:
      allow: true
      publicKeyName: airflow-workstation
    labels: { role: manager }
    tags:
      nodegroup-role: manager
    iam:
      withAddonPolicies:
        ebs: true
        imageBuilder: true
        efs: true
        albIngress: true
        autoScaler: true
        cloudWatch: true
        externalDNS: true
  - name: shap
    instanceType: r5.large
    privateNetworking: true
    minSize: 1
    maxSize: 5
    desiredCapacity: 1
    volumeSize: 100
    availabilityZones: ['ap-northeast-2a', 'ap-northeast-2d', 'ap-northeast-2c']
    ssh:
      allow: true
      publicKeyName: airflow-workstation
    labels: { role: shap }
    tags:
      nodegroup-role: shap
    iam:
      withAddonPolicies:
        ebs: true
        imageBuilder: true
        efs: true
        albIngress: true
        autoScaler: true
        cloudWatch: true
        externalDNS: true
  - name: event-stream
    instanceType: t3.medium
    privateNetworking: true
    minSize: 3
    maxSize: 6
    desiredCapacity: 3
    volumeSize: 100
    availabilityZones: ['ap-northeast-2a', 'ap-northeast-2d', 'ap-northeast-2c']
    ssh:
      allow: true
      publicKeyName: airflow-workstation
    labels: { role: event-stream }
    tags:
      nodegroup-role: event-stream
    iam:
      withAddonPolicies:
        ebs: true
        imageBuilder: true
        efs: true
        albIngress: true
        autoScaler: true
        cloudWatch: true
        externalDNS: true